runtime: python310
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  FLASK_APP: "app.py"
  SECRET_KEY: "562100"
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:562100@/bookstore?unix_socket=/cloudsql/balmy-gearing-404209:us-central1:bookstore"

beta_settings:
  cloud_sql_instances: "balmy-gearing-404209:us-central1:bookstore"

entrypoint: gunicorn -b :8080 app:app
